version: '3.9'
services:
  postgres_ny:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: 'taxi_ny'
      POSTGRES_PASSWORD: 'taxi_ny'
      POSTGRES_DB: 'taxi_ny'  
    ports:
      - 5432:5432
    volumes:
      - pg_data_ny:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'taxi_ny']
      interval: 5s
      retries: 5
  #postgres:
  #  image: postgres:15.1
  #  restart: always
  #  environment:
  #    POSTGRES_USER: 'airflow'
  #    POSTGRES_PASSWORD: 'airflow'
  #    POSTGRES_DB: 'airflow'  
  #  ports:
  #    - 5432:5432
  #  volumes:
  #    - pg_data_ny:/var/lib/postgresql/data
  #  healthcheck:
  #    test: ['CMD', 'pg_isready', '-U', 'airflow']
  #    interval: 5s
  #    retries: 5
volumes:
  pg_data_ny: